first_num = float(input("Enter the first Number :"))
second_num = float(input("Enter the second Number :"))
print("ADD :", (first_num + second_num))
print("SUB :", (first_num - second_num))
print("MUL :", (first_num * second_num))
print("DIV :", (first_num / second_num))
